name: Test MLOps Pipeline (DVC + DAGsHub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    env:
      DAGSHUB_USERNAME: b.manmadharao207
      DAGSHUB_TOKEN: c3c8546a06461326870a6557917cf6ac27848641

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install dvc[s3] mlflow -r requirements.txt

      - name: Configure DVC Remote (DAGsHub)
        run: |
          dvc remote remove dagshub || true
          dvc remote add -f dagshub s3://dvc
          dvc remote modify dagshub endpointurl https://dagshub.com/b.manmadharao207/manu7-end-to-end-mlops-project.s3
          dvc remote modify dagshub --local access_key_id $DAGSHUB_USERNAME
          dvc remote modify dagshub --local secret_access_key $DAGSHUB_TOKEN
          dvc remote default dagshub
          dvc remote list

      - name: DVC Pull
        run: dvc pull -v

      - name: Run DVC Pipeline
        run: dvc repro

      - name: DVC Push
        run: dvc push

      - name: Commit dvc.lock
        run: |
          git config --global user.email "mlops-test@github.com"
          git config --global user.name "mlops-test"
          git add dvc.lock
          git commit -m "Test run: DVC + DAGsHub" || echo "No changes"
          git push origin main
